export const GET_BRANDS_LOADING = "GET_BRANDS_LOADING";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_ERROR";
export const GET_BRANDS_ERROR = "GET_BRANDS_ERROR";
export const GET_BRANDS = "GET_BRANDS";

export const CREATE_BRANDS = "CREATE_BRANDS";
export const CREATE_BRANDS_SUCCESS = "CREATE_BRANDS_SUCCESS";

export const UPDATE_BRANDS = "UPDATE_BRANDS";
export const UPDATE_BRANDS_SUCCESS = "UPDATE_BRANDS_SUCCESS";

export const DELETE_BRANDS = "DELETE_BRANDS";
export const DELETE_BRANDS_SUCCESS = "DELETE_BRANDS_SUCCESS";
