export const GET_BRANDS_LOADING = "GET_BRANDS_LOADING";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_ERROR";
export const GET_BRANDS_ERROR = "GET_BRANDS_ERROR";
export const GET_BRANDS = "GET_BRANDS";
