export const GET_GROUPS_LOADING = "GET_GROUPS_LOADING";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_ERROR";
export const GET_GROUPS_ERROR = "GET_GROUPS_ERROR";
export const GET_GROUPS = "GET_GROUPS";
