export const GET_GROUPS_LOADING = "GET_GROUPS_LOADING";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_ERROR";
export const GET_GROUPS_ERROR = "GET_GROUPS_ERROR";
export const GET_GROUPS = "GET_GROUPS";

export const CREATE_GROUPS = "CREATE_GROUPS";
export const CREATE_GROUPS_SUCCESS = "CREATE_GROUPS_SUCCESS";

export const UPDATE_GROUPS = "UPDATE_GROUPS";
export const UPDATE_GROUPS_SUCCESS = "UPDATE_GROUPS_SUCCESS";

export const DELETE_GROUPS = "DELETE_GROUPS";
export const DELETE_GROUPS_SUCCESS = "DELETE_GROUPS_SUCCESS";
