export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_LOADING = "GET_ORDERS_LOADING";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR";

export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";

export const CREATE_ORDERS = "CREATE_ORDERS";
export const CREATE_ORDERS_SUCCESS = "CREATE_ORDERS_SUCCESS";

export const DELETE_ORDERS = "DELETE_ORDERS";
export const DELETE_ORDERS_SUCCESS = "DELETE_ORDERS_SUCCESS";
