export const GET_STORES_LOADING = "GET_STORES_LOADING";
export const GET_STORES_SUCCESS = "GET_STORES_ERROR";
export const GET_STORES_ERROR = "GET_STORES_ERROR";
export const GET_STORES = "GET_STORES";
