export const GET_STORES_LOADING = "GET_STORES_LOADING";
export const GET_STORES_SUCCESS = "GET_STORES_ERROR";
export const GET_STORES_ERROR = "GET_STORES_ERROR";
export const GET_STORES = "GET_STORES";

export const CREATE_STORES = "CREATE_STORES";
export const CREATE_STORES_SUCCESS = "CREATE_STORES_SUCCESS";

export const UPDATE_STORES = "UPDATE_STORES";
export const UPDATE_STORES_SUCCESS = "UPDATE_STORES_SUCCESS";

export const DELETE_STORES = "DELETE_STORES";
export const DELETE_STORES_SUCCESS = "DELETE_STORES_SUCCESS";
