export const GET_CATEGORYS_LOADING = "GET_CATEGORYS_LOADING";
export const GET_CATEGORYS_SUCCESS = "GET_CATEGORYS_SUCCESS";
export const GET_CATEGORYS_ERROR = "GET_CATEGORYS_ERROR";
export const GET_CATEGORYS = "GET_CATEGORYS";

export const CREATE_CATEGORYS = "CREATE_BRANDS";
export const CREATE_CATEGORYS_SUCCESS = "CREATE_CATEGORYS_SUCCESS";

export const UPDATE_CATEGORYS = "UPDATE_CATEGORYS";
export const UPDATE_CATEGORYS_SUCCESS = "UPDATE_CATEGORYS_SUCCESS";

export const DELETE_CATEGORYS = "DELETE_CATEGORYS";
export const DELETE_CATEGORYS_SUCCESS = "DELETE_CATEGORYS_SUCCESS";
