export const GET_CATEGORYS_LOADING = "GET_CATEGORYS_LOADING";
export const GET_CATEGORYS_SUCCESS = "GET_CATEGORYS_SUCCESS";
export const GET_CATEGORYS_ERROR = "GET_CATEGORYS_ERROR";
export const GET_CATEGORYS = "GET_CATEGORYS";
