export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const REMOVE_PROFILE_SUCCESS = "REMOVE_PROFILE_SUCCESS";
