export const GET_ATTRIBUTES_LOADING = "GET_ATTRIBUTES_LOADING";
export const GET_ATTRIBUTES_SUCCESS = "GET_ATTRIBUTES_ERROR";
export const GET_ATTRIBUTES_ERROR = "GET_ATTRIBUTES_ERROR";
export const GET_ATTRIBUTES = "GET_ATTRIBUTES";

export const CREATE_ATTRIBUTES = "CREATE_ATTRIBUTES";
export const CREATE_ATTRIBUTES_SUCCESS = "CREATE_ATTRIBUTES_SUCCESS";

export const UPDATE_ATTRIBUTES = "UPDATE_ATTRIBUTES";
export const UPDATE_ATTRIBUTES_SUCCESS = "UPDATE_ATTRIBUTES_SUCCESS";

export const DELETE_ATTRIBUTES = "DELETE_ATTRIBUTES";
export const DELETE_ATTRIBUTES_SUCCESS = "DELETE_ATTRIBUTES_SUCCESS";
